theme: jekyll-theme-basically-basic
title: "yzp's notes"
logo: /assets/icons/icons8-maple-leaf-50.png
url: https://turnon.github.io/
email: 1020715764@qq.com
github_username: turnon

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
